# Generated by Django 6.0.5 on 2026-05-07 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0002_pendinguser_delete_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendinguser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='pendinguser',
            name='username',
        ),
    ]
