# Generated by Django 6.0.5 on 2026-05-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0003_remove_pendinguser_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinguser',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
