# Generated by Django 6.0.5 on 2026-05-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0005_alter_pendinguser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record should be treated as active.')),
            ],
        ),
    ]
