# Generated by Django 6.0.5 on 2026-05-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0007_category_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
