# Generated by Django 6.0.5 on 2026-05-09 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0009_remove_category_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(null=True)),
                ('stock', models.IntegerField(null=True)),
                ('ia_available', models.BooleanField(default=True, help_text='Product is available or not')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.category')),
            ],
        ),
    ]
