# Generated by Django 6.0.5 on 2026-05-09 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0010_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ia_available',
            new_name='is_available',
        ),
    ]
