# Generated by Django 6.0.5 on 2026-05-12 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0013_alter_cart_item_cart_alter_cart_item_quantity_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
