# Generated by Django 6.0.5 on 2026-05-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0014_remove_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_item',
        ),
        migrations.AddField(
            model_name='order',
            name='cart_item',
            field=models.ManyToManyField(to='ecom_app.cart_item'),
        ),
    ]
