# Generated by Django 6.0.5 on 2026-05-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0016_remove_order_cart_remove_order_cart_item_order_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_item',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
