# Generated by Django 6.0.5 on 2026-05-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0022_remove_order_item_order_remove_order_item_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
