# Generated by Django 6.0.5 on 2026-05-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0025_deliverypartner'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypartner',
            name='Product',
            field=models.ManyToManyField(to='ecom_app.product'),
        ),
    ]
