# Generated by Django 6.0.5 on 2026-05-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0026_deliverypartner_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypartner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
