# Generated by Django 6.0.5 on 2026-05-14 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0027_deliverypartner_created_at_deliverypartner_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverypartner',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='deliverypartner',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='deliverypartner',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='deliverypartner',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='deliverypartner',
            name='total_price',
        ),
        migrations.AddField(
            model_name='checkout',
            name='delivery_partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom_app.deliverypartner'),
        ),
    ]
