# Generated by Django 6.0.5 on 2026-05-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0028_remove_deliverypartner_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
