# Generated by Django 6.0.5 on 2026-05-14 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0029_checkout_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='cancel_reason',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='delivery_partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkout_list', to='ecom_app.deliverypartner'),
        ),
    ]
