# Generated by Django 6.0.5 on 2026-05-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0030_checkout_cancel_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='cancel_reason',
            field=models.CharField(default='N/A', max_length=100, null=True),
        ),
    ]
